### PR TITLE
Add celluloid for concurrency

### PR DESCRIPTION
**Pull request by fnichol**
Here's where the work is going down.

### CODE REVIEW

**Comment by sethvargo** [comment]
:+1:

**Comment by sethvargo** [comment]
I love how it keeps the same level of readability too!

**Comment by fnichol** [comment]
Sorry there, a rare moment of force push from a rebased master. Not a common practice for me but I doubt anyone is tracking this branch in code at the moment.

**Comment by fnichol** [comment]
@sethvargo Yeah, no kidding. Just working out a supervisor actor for crashed instances (most likely `Jamie::Config`) and a flag for the CLI instance actions (maybe `--parallel`/`-p`). After that things should be pretty functional.

**Comment by sethvargo** [comment]
Lol I'm tracking :), but I can do a reset

**Comment by fnichol** [comment]
Should be able to put this branch to bed tonight, so far celluloid has been a pleasure.

**Comment by fnichol** [comment]
And that's a wrap!

**Pull request merged**
